### ISSUE TITLE
将统计代码添加到部分网站会让排版出现异常

### ISSUE THREAD

**Issue by lm379** [yestool/analytics_with_cloudflare#4]
通过下面的代码引用统计程序使得整个站点排版混乱
```html
<script defer src="//webviso.yestool.org/js/index.min.js"></script>
本页访问人次:<span id="page_pv"> </span>本页访问人数:<span id="page_uv"></span>
```
添加到Alist后的效果
![image](https://github.com/yestool/analytics_with_cloudflare/assets/69002314/87dc2c0f-e079-425c-9879-702ee236219c)

添加到hexo博客的效果
![image](https://github.com/yestool/analytics_with_cloudflare/assets/69002314/f77e318e-7742-419a-9191-137203547408)

但是看了下统计次数的功能是生效的
![image](https://github.com/yestool/analytics_with_cloudflare/assets/69002314/138e4d26-5640-4100-b3ab-228b32b34e42)

**Comment by yestool** [comment]
您这个貌似与我的程序没关系。您页面排版有问题可能的原因是cdn被广告插件屏蔽  [见规则](https://github.com/uBlockOrigin/uAssets/pull/24285)
